site_name: Infra Docs
repo_url: https://github.com/v-grand/infra-docs

theme:
  name: material
  features:
    - navigation.tabs
  language: en
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  palette:
    scheme: default
  icon:
    repo: fontawesome/brands/github

nav:
  - 'en':
    - 'Home': 'en/index.md'
    - 'Infra Core': 'en/infra-core.md'
    - 'Examples':
      - 'AWS Dev': 'en/examples/aws-dev.md'
    - 'AWS': 'en/aws.md'
    - 'GCP': 
      - 'Home': 'en/gcp/index.md'
      - 'VM': 'en/gcp/vm.md'
      - 'DB': 'en/gcp/db.md'
      - 'K8s': 'en/gcp/k8s.md'
    - 'Tailscale': 'en/tailscale.md'
    - 'Notebooks':
      - 'Example': 'notebooks/example.md'
      - 'CI/CD Pipeline': 'notebooks/ci-cd-pipeline.md'
      - 'Infra Core Usage': 'notebooks/infra-core-usage.md'
      - 'Tailscale Mesh': 'notebooks/tailscale-mesh.md'
      - 'Terraform Demo': 'notebooks/terraform-demo.md'
  - 'ru':
    - 'Home': 'ru/index.md'
    - 'Infra Core': 'ru/infra-core.md'
    - 'Examples':
      - 'AWS Dev': 'ru/examples/aws-dev.md'
    - 'AWS': 'ru/aws.md'
    - 'GCP': 
      - 'Home': 'ru/gcp/index.md'
      - 'VM': 'ru/gcp/vm.md'
      - 'DB': 'ru/gcp/db.md'
      - 'K8s': 'ru/gcp/k8s.md'
    - 'Tailscale': 'ru/tailscale.md'
    - 'Notebooks':
      - 'Example': 'notebooks/example.md'
      - 'CI/CD Pipeline': 'notebooks/ci-cd-pipeline.md'
      - 'Infra Core Usage': 'notebooks/infra-core-usage.md'
      - 'Tailscale Mesh': 'notebooks/tailscale-mesh.md'
      - 'Terraform Demo': 'notebooks/terraform-demo.md'
  - 'pl':
    - 'Home': 'pl/index.md'
    - 'Infra Core': 'pl/infra-core.md'
    - 'Examples':
      - 'AWS Dev': 'pl/examples/aws-dev.md'
    - 'AWS': 'pl/aws.md'
    - 'GCP': 
      - 'Home': 'pl/gcp/index.md'
      - 'VM': 'pl/gcp/vm.md'
      - 'DB': 'pl/gcp/db.md'
      - 'K8s': 'pl/gcp/k8s.md'
    - 'Tailscale': 'pl/tailscale.md'
    - 'Notebooks':
      - 'Example': 'notebooks/example.md'
      - 'CI/CD Pipeline': 'notebooks/ci-cd-pipeline.md'
      - 'Infra Core Usage': 'notebooks/infra-core-usage.md'
      - 'Tailscale Mesh': 'notebooks/tailscale-mesh.md'
      - 'Terraform Demo': 'notebooks/terraform-demo.md'

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ru: Русский
        pl: Polski
  # - jupyter

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      baselevel: 2
