site_name: Infra Docs
repo_url: https://github.com/v-grand/infra-docs

theme:
  name: material
  features:
    - navigation.tabs
  language: en
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  palette:
    scheme: default
  icon:
    repo: fontawesome/brands/github

nav:
  - 'en':
    - 'Home': 'en/index.md'
    - 'Infra Core': 'en/infra-core.md'
    - 'Examples':
      - 'AWS Dev': 'en/examples/aws-dev.md'
    - 'AWS': 'en/aws.md'
    - 'GCP': 
      - 'Home': 'en/gcp/index.md'
      - 'VM': 'en/gcp/vm.md'
      - 'DB': 'en/gcp/db.md'
      - 'K8s': 'en/gcp/k8s.md'
    - 'Tailscale': 'en/tailscale.md'
  - 'ru':
    - 'Home': 'ru/index.md'
    - 'AWS': 'ru/aws.md'
    - 'GCP': 
      - 'Home': 'ru/gcp/index.md'
    - 'Tailscale': 'ru/tailscale.md'
  - 'pl':
    - 'Home': 'pl/index.md'
    - 'AWS': 'pl/aws.md'
    - 'GCP': 
      - 'Home': 'pl/gcp/index.md'
    - 'Tailscale': 'pl/tailscale.md'

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ru: Русский
        pl: Polski
  # - jupyter